FROM oven/bun:latest

WORKDIR /app

COPY package.json bun.lock ./

COPY common/package.json ./common/
COPY web/package.json ./web/
COPY cli/package.json ./cli/
COPY video/package.json ./video/

RUN bun install --frozen-lockfile 

COPY . . 
